services:

  postgres:
    image: postgres:18
    container_name: bookstore-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - bookstore-network


  app:
    build:
      context: .

    image: mag-lab3-app:1.0

    container_name: bookstore-app

    env_file:
      - .env

    stdin_open: true
    tty: true

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./logs:/app/logs

    networks:
      - bookstore-network


volumes:
  postgres-data:


networks:
  bookstore-network:
    driver: bridge